projet ecommerce/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

projet ecommerce/ecommerce/shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import connexion, produit_quantite,register, createproduits, deconnexion, deleteproduits, detail, index, table, updateproduits

urlpatterns = [
    
    path('', index, name='index'),
    path('create/', createproduits, name='create'),
    path('<int:myid>/', detail, name='detail'),
    path('table/update/<int:id>/', updateproduits, name='update'),
    path('table/', table, name='table'),
    path('table/delete/<int:id>/', deleteproduits, name='delete'),
    path('login/', connexion, name='login'),
    path('logout/', deconnexion, name='logout'),
    path('register/', register, name='register'),
    path('produit_quantit/', produit_quantite, name='produit_quantite'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projet ecommerce/ecommerce/shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    nom=models.CharField(max_length=250)
    date_ajout=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=['-date_ajout']

    def __str__(self):
        return self.nom

class Product(models.Model):
    nom=models.CharField(max_length=250)
    prix=models.FloatField()
    description=models.TextField()
    categorie=models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    date_ajout=models.DateTimeField(auto_now_add=True)
    quantite_en_stock = models.PositiveIntegerField(default=0) 
    class Meta:
        ordering=['-date_ajout']

   
    def quantite_disponible(self):
        if self.quantite_en_stock > 5:
            return 'green'
        elif 0 < self.quantite_en_stock <= 5:
            return 'orange'
        else:
            return 'red'
    

    def __str__(self):
        return self.nom

projet ecommerce/ecommerce/shop/views.py
from django.shortcuts import get_object_or_404, redirect, render

from shop.form import CreateProduct, UserForm
from .models import Category, Product
from django.core.paginator import Paginator

# pour authentification
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# pour les messages
from django.contrib import messages


# Create your views here.

def index(request):
    # if not request.user.is_authenticated:
    #     return redirect('login')  # Redirection vers la page de connexion

    produits = Product.objects.all()
    
    # pour rechercher un produit
    items_name = request.GET.get('item-name', '').strip()  # Nettoyage de la chaîne de recherche
    if items_name:  # Vérifie si la chaîne n'est pas vide après nettoyage
        produits = produits.filter(nom__icontains=items_name)
        if not produits.exists():  # Vérifie s'il y a des résultats
            return render(request, 'shop/index.html', {'message': 'Désolé, ce produit n\'existe pas'})

    # pour la pagination
    paginator = Paginator(produits, 8)
    page = request.GET.get('page')
    produits = paginator.get_page(page)

    context = {"produits": produits}
    return render(request, "shop/index.html", context)


def detail(request, myid):
    produits = Product.objects.get(id=myid)
    return render(request, 'shop/detail.html', {'produits':produits})
@login_required
def table(request):
    produits = Product.objects.all()
    return render(request, 'shop/table.html', {'produits':produits})

def createproduits(request):
    form = CreateProduct()
    categories = Category.objects.all()  # Récupérer toutes les catégories
    

    if request.method == 'POST':
        form = CreateProduct(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form = CreateProduct()
            messages.success(request,'le produits a bien ete ajouté avec succes')
        else :
            messages.error(request,'le produits n\'a pas pu etre ajouté')

    return render(request, 'shop/createproduits.html', {
        "form": form,
        
        "categories": categories  # Passer les catégories au template
    })

def updateproduits(request, id):
    produits = get_object_or_404(Product, id=id)
    message=""
    form = CreateProduct(instance=produits)
    if request.method == 'POST':
        form = CreateProduct(request.POST, request.FILES, instance=produits)
        if form.is_valid():
            form.save()
            # vider le formulaire
            form = CreateProduct()
            message="le produits a bien ete modifié"
    return render(request, 'shop/updateproduit.html', {'form':form,'message':message})

def deleteproduits(request, id):
    message=""
    produits = get_object_or_404(Product, id=id)
    if request.method == 'POST':
        produits.delete()
        message="le produits a bien ete supprimé"
        return redirect('table')
    
    return render(request, 'shop/delete.html', {'produits':produits,'message':message})


def register(request):
    form=UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'votre compte a bien été crée')
            return redirect('login')
        else:
            messages.error(request, 'votre compte n\'a pas été crée')

    return render(request, 'shop/register.html', {'form':form})


def connexion(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Connexion reussie')
            return redirect('table')
        else:
            messages.error(request, 'Votre identifiant ou mot de passe est incorrect')
    return render(request, 'shop/login.html')
@login_required
def deconnexion(request):
    logout(request)
    return redirect('login')

def produit_quantite(request):
    produits = Product.objects.all()
    for produit in produits:
        if produit.quantite_en_stock < 5:
            messages.warning(request, f"Le stock du produit {produit.nom} est faible ({produit.quantite_en_stock} restants).")
    return render(request, 'shop/produit_list.html', {'produits': produits})



    
            
            
            

projet ecommerce/ecommerce/shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <!-- Métadonnées -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GERALD-shop</title>

    <!-- CSS personnalisé -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.1.js"
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="#">GERALD-shop</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'index' %}">Accueil<span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'table' %}">Nos Produits</a>
                            </li>
                            <li class="nav-item">
                                <a id="panier" class="nav-link" href="#">Panier (0)</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Catégories
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        </ul>

                        <!-- Liens de login, register et logout alignés à droite -->
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}">
                                    <i class="fas fa-sign-in-alt"></i> Connexion
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'register' %}">
                                    <i class="fas fa-user-plus"></i> S'inscrire
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">
                                    <i class="fas fa-sign-out-alt"></i> Déconnexion
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>

        {% block content %}
        {% endblock %}
    </div>

</body>

{% block js %}
{% endblock %}

</html>

projet ecommerce/ecommerce/shop/templates/shop/createproduits.html
{% extends 'shop/base.html' %}
{% block content %}
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-sm">
                    <div class="card-header bg-primary text-white text-center">
                        <h2>Ajouter un Nouveau Produit</h2>
                    </div>
                    <div class="card-body">
                        {% for messe in messages %}
                        <div class="alert alert-success text-center">{{ messe }}</div>
                        {% endfor %}
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_nom">Nom du Produit</label>
                                <input type="text" name="nom" class="form-control"
                                    placeholder="Entrez le nom du produit" required>
                            </div>
                            <div class="form-group">
                                <label for="id_prix">Prix</label>
                                <input type="number" name="prix" class="form-control"
                                    placeholder="Entrez le prix du produit" required>
                            </div>
                            <div class="form-group">
                                <label for="id_description">Description</label>
                                <textarea name="description" class="form-control" rows="4"
                                    placeholder="Entrez une description détaillée" required></textarea>
                            </div>
                            <div class="form-group">
                                <label for="id_categorie">Catégorie</label>
                                <select name="categorie" class="form-control" required>
                                    <!-- Les options des catégories seront générées dynamiquement -->
                                        {% for categorie in categories %}
                                            <option value="{{ categorie.id }}">{{ categorie.nom }}</option>
                                        {% endfor %}
                                    
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="id_image">Image du Produit</label>
                                <input type="file" name="image" class="form-control-file" required>
                            </div>
                            <!-- pour la quantité en stock -->
                            <div class="form-group">
                                <label for="id_quantite_en_stock">Quantité en stock</label>
                                <input type="number" name="quantite_en_stock" class="form-control"
                                    placeholder="Entrez la quantité en stock" required>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-success btn-lg">Ajouter le Produit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
    <!-- Bootstrap JS -->
     {% block js %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    {% endblock %}

projet ecommerce/ecommerce/shop/templates/shop/delete.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Supprimer un Produit</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-sm">
                    <div class="card-header bg-danger text-white text-center">
                        <h2>Supprimer le Produit</h2>
                    </div>
                    <div class="card-body">
                        {% if message %}
                        <div class="alert alert-success text-center">{{ message }}</div>
                        {% else %}
                        <div class="text-center">
                            <h5>Êtes-vous sûr de vouloir supprimer ce produit ?</h5>
                            <h2><strong>{{ produits.nom }}</strong></h2>
                            <p>Prix : {{ produits.prix }} FCFA</p>
                            <img src="{{ produits.image.url }}" alt="{{ produits.nom }}" class="img-thumbnail"
                                style="width: 150px;">
                        </div>
                        <hr>
                        <div class="text-center">
                            <form method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-lg btn-sm">Supprimer</button>
                                <a href="{% url 'table' %}" class="btn btn-secondary btn-lg btn-sm">Annuler</a>
                            </form>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

projet ecommerce/ecommerce/shop/templates/shop/detail.html
{% extends 'shop/base.html' %}
{% block content %}
<div class="row mt-5">
    <div class="col-md-6">
        <div>
            <img src="{{produits.image.url}}" width="500px" height="500px" alt="" >
        </div>
    </div>
        <div class="col-md-6">
            <div class="text-warning display-3">{{ produits.nom }}</div>
            <div class="text-danger">prix: {{ produits.prix }}</div>
            <div>description: {{ produits.description }}</div>
            <div class="display-3">
                <a href="" class=" btn btn-success btn-sm">Acheter</a>
                <a class=" btn btn-primary btn-sm" href="{% url 'index' %}">acceuil</a>
            </div>
            
        </div>
        
</div>
{% endblock %}

projet ecommerce/ecommerce/shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <form class="card card-sm">
            <div class="card-body row no-gutters align-items-center">
                <div class="col">
                     <input name="item-name" type="search" class="form-control form-control-borderless" placeholder="entrez le nom du produit que vous cherchez">
                     {% if message %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-success">Rechercher</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    {% for produit in produits %}
    <div class="col-md-3">
        <div class="card">
            <img src="{{produit.image.url}}" alt="" class="card-img-top">
            <div class="card-body">
                <div style="color: black;" class="card-title">{{ produit.nom }}</div>
                <div style="color:orangered;" class="card-text">{{ produit.prix }} FCFA</div>
                <a href="{% url 'detail' produit.id %}"class="btn btn-warning btn-sm"><i class="fas fa-eye"></i> Voire</a>
                <button id="{{ produit.id }}" class="btn ted btn-success btn-sm"><i class="fas fa-plus"></i> Ajouter</button>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="row mt-3">
    <div class="col-md-3 offset-md-4">
        <ul class="pagination">
            {% if produits.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ produits.previous_page_number }}">precedent</a>
            </li>
            {% endif %}

            <li class="page-item active">
                <a class="page-link" href="?page={{ produits.number }}">{{ produits.number }}</a>

            </li>

            {% if produits.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ produits.next_page_number }}">suivant</a>
            </li>
            {% endif %}

        </ul>
    </div>
   
</div>

{% endblock %}

{% block js %}
    <script type="text/javascript">
        console.log("juste pour tester");
        if(localStorage.getItem("panier") === null){
            var panier = {};}
            else{
                panier = JSON.parse(localStorage.getItem("panier"));
            }
            $(document).on("click", ".ted", function(){
                console.log("ajouter");
            var item_id = this.id.toString();
            console.log(item_id);
            if (panier[item_id] != undefined){
                panier[item_id] += 1;}
                else{
                    panier[item_id] = 1;
                }
                console.log(panier);
                localStorage.setItem("panier", JSON.stringify(panier));
                document.getElementById("panier").innerHTML = "panier(" + Object.keys(panier).length + ")" 
            
            });

    </script>

   
{% endblock %}

projet ecommerce/ecommerce/shop/templates/shop/login.html
{% extends 'shop/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-lg">
                <div class="card-header text-center bg-success text-white">
                    <h3>Connexion</h3>
                </div>
                <div class="card-body">
                    {% for message in messages %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% endfor %}

                    <form method="post" action="{% url 'login' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Nom d'utilisateur</label>
                            <input type="text" name="username" class="form-control" id="username"
                                placeholder="Entrez votre nom" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="password">Mot de passe</label>
                            <input type="password" name="password" class="form-control" id="password"
                                placeholder="Entrez votre mot de passe" required>
                        </div>
                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-success btn-block">Se connecter</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

projet ecommerce/ecommerce/shop/templates/shop/register.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center" style="height: 100%;">
        <!-- Colonne pour l'image -->
        <!-- <div class="col-md-6 d-none d-md-block">
            <div class="card h-100">
                <img src="{% static 'images/register_image.jpg' %}" class="img-fluid h-100" alt="Register Image"
                    style="object-fit: cover; border-radius: 10px;">
            </div>
        </div> -->

        <!-- Colonne pour le formulaire d'enregistrement -->
        <div class="col-md-6">
            <div class="card h-100 shadow-lg">
                <div class="card-header text-center bg-success text-white">
                    <h3>Enregistrement</h3>
                </div>
                <div class="card-body d-flex align-items-center">
                    <form method="post" action="{% url 'register' %}" class="w-100">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Nom d'utilisateur</label>
                            <input type="text" name="username" class="form-control" id="username"
                                placeholder="Entrez votre nom" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="email">Adresse e-mail</label>
                            <input type="email" name="email" class="form-control" id="email"
                                placeholder="Entrez votre e-mail" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="password1">Mot de passe</label>
                            <input type="password" name="password1" class="form-control" id="password1"
                                placeholder="Entrez votre mot de passe" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="password2">Confirmer le mot de passe</label>
                            <input type="password" name="password2" class="form-control" id="password2"
                                placeholder="Confirmez votre mot de passe" required>
                        </div>
                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-success btn-block">S'enregistrer</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

projet ecommerce/ecommerce/shop/templates/shop/updateproduit.html
{% extends 'shop/base.html' %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-lg">
                    <div class="card-header bg-primary text-white text-center">
                        <h2>Modifier le Produit</h2>
                    </div>
                    <div class="card-body">
                        {% if message %}
                        <div class="alert alert-success text-center">{{ message }}</div>
                        {% endif %}
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- Nom du produit -->
                            <div class="form-group">
                                <label for="id_nom">Nom du Produit</label>
                                <input type="text" name="nom" class="form-control" value="{{ form.nom.value }}"
                                    placeholder="Entrez le nom du produit" required>
                            </div>

                            <!-- Prix du produit -->
                            <div class="form-group">
                                <label for="id_prix">Prix</label>
                                <input type="number" step="0.01" name="prix" class="form-control" value="{{ form.prix.value|floatformat }}"
                                    placeholder="Entrez le prix du produit" required>
                            </div>


                            <!-- Description du produit -->
                            <div class="form-group">
                                <label for="id_description">Description</label>
                                <textarea name="description" class="form-control" rows="4"
                                    placeholder="Entrez une description détaillée"
                                    required>{{ form.description.value }}</textarea>
                            </div>
                            
                            <!-- pour la quantité en stock -->
                            <div class="form-group">
                                <label for="id_quantite_en_stock">quantité en stock</label>
                                <input type="number" name="quantite_en_stock" class="form-control" value="{{ form.quantite_en_stock.value }}"  placeholder="Entrez la quantité en stock"
                                    required>
                            </div>
                           

                            <!-- Catégorie du produit -->
                            <div class="form-group">
                                <label for="id_categorie">Catégorie</label>
                                <select name="categorie" class="form-control" required>
                                    {% for categorie in form.categorie.field.queryset %}
                                    <option value="{{ categorie.id }}" {% if categorie.id == form.categorie.value %}selected{% endif %}>{{ categorie.nom }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <!-- Image du produit -->
                        <div class="form-group">
                            <label for="id_image">Image du Produit</label>
                            <input type="file" name="image" class="form-control-file">
                            {% if produits.image %}
                            <!-- Afficher l'image actuelle -->
                            <div class="mt-3">
                                <img src="{{ produits.image.url }}" alt="Image actuelle" class="img-thumbnail" style="width: 150px;">
                            </div>
                            {% endif %}
                        </div>


                            <!-- Bouton de modification -->
                            <div class="text-center">
                                <button type="submit" class="btn btn-success btn-lg">Modifier le Produit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


    {% block js %}
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    {% endblock %}